spring:
  application:
    name: CarMaintananceRecorder
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/car_maintanance_db}
    #    url: jdbc:postgresql://localhost:15432/car_maintanance_db
    #    url: jdbc:postgresql://192.168.89.100:5432/car_maintanance_db
    #    username: ${SPRING_DATASOURCE_USER:martinv}
    #    password: ${SPRING_DATASOURCE_PASSWORD:Password123@}
    username: ${SPRING_DATASOURCE_USER:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    #    username: postgres
    #    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default-schema: car_maintanance_db
        show_sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.yaml
    default-schema: car_maintanance_db
display:
  name: Hello ${project.name}
project:
  name: "Car Maintanance Recorder"
logging:
  config: classpath:log4j2.xml

jakarta:
  persistence:
    jdbc:
      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/car_maintanance_db}
